version: "3"

services:
    frontend:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./faucet_frontend:/usr/share/nginx/html
    backend:
        build: ./endpoint
        command: bash -c "uvicorn main:app --workers 1 --host 0.0.0.0 --port 5000"
        restart: unless-stopped
        ports:
          - "5000:5000"
        environment:
          NODE_URL: ""
          MNEMONIC: ""